drop table if exists users, items, bookings, comments;

create table if not exists users(
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(512) not null unique
);

create table if not exists items(
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(1000) not null,
    is_available boolean not null,
    owner_id bigint not null references users(id)
);

create table if not exists bookings(
    id bigint generated by default as identity primary key,
    start_date timestamp without time zone not null,
    end_date timestamp without time zone not null,
    item_id bigint not null references items(id),
    booker_id bigint not null references users(id),
    status varchar(255) not null
);

create table if not exists comments(
    id bigint generated by default as identity primary key,
    text varchar(2000) not null,
    item_id bigint references items(id),
    author_id bigint references users(id),
    created timestamp without time zone not null
);